// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhhfaxbrwefmsmxvtoah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaGZheGJyd2VmbXNteHZ0b2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTE0NjEsImV4cCI6MjA3MTQyNzQ2MX0.yD4eOAsWKHRWS82GeTTAsvLuxN6j7YmIBqC69v98Z2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});